"""create base tables: lockers, gminy, nuts2, population, snapshots

Revision ID: 5d424a72bd30
Revises:
Create Date: 2026-05-12 22:54:49.965590

The schema bedrock. Creates seven tables in dependency order:

- gminy   (Polish gminas, MULTIPOLYGON SRID 2180 — native PUWG 1992)
- nuts2   (EU NUTS-2 regions, MULTIPOLYGON SRID 4326 from Eurostat)
- lockers (current snapshot of all InPost pickup points, geography(Point,4326);
           FKs to gminy.teryt and nuts2.code populated via post-ingest spatial
           join in ingest/sync.py)
- population_gmina, population_nuts2 (yearly population values keyed by FK)
- ingest_snapshots (time-series of locker state — promoted to a TimescaleDB
                    hypertable in this same migration via create_hypertable())

Two non-obvious details worth understanding before reading the upgrade body:

1. h3 GENERATED columns. lockers has h3_r6 + h3_r8 columns declared as
   STORED GENERATED from the geom point via h3_lat_lng_to_cell(). Stored
   (not virtual) so the GIST indexes on them are usable. Migrating off h3
   later means dropping the column AND the generated expression.

2. Hypertable promotion. ingest_snapshots is a regular table at CREATE TABLE
   time, then promoted to a TimescaleDB hypertable with a 30-day chunk
   interval, compress_segmentby='country, is_locker', and add_compression_policy
   firing after 14 days + add_retention_policy after 730 days. The model in
   models/snapshot.py only describes the table shape — the hypertable
   conversion is migration-only state.

GIST indexes on geom columns are created by GeoAlchemy2's default
spatial_index=True. Don't add explicit op.create_index(..., postgresql_using='gist')
on those columns — autogenerate emits both and the second one collides at
apply time with `relation already exists`.
"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d424a72bd30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Defensive: extensions should already exist via docker-entrypoint-initdb.d.
    # Re-asserting them here so fresh deploys (e.g. CI databases) work without
    # depending on the compose init scripts.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS h3")
    op.execute("CREATE EXTENSION IF NOT EXISTS h3_postgis CASCADE")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_cron")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gminy',
    sa.Column('teryt', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('voivodeship', sa.String(length=64), nullable=True),
    sa.Column('powiat', sa.String(length=128), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2180, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_km2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('teryt')
    )
    # idx_gminy_geom GIST index auto-created by GeoAlchemy2 (spatial_index=True)
    op.create_table('ingest_snapshots',
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locker_name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_locker', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_at', 'locker_name', name='pk_ingest_snapshots')
    )
    # idx_ingest_snapshots_geom GIST index auto-created by GeoAlchemy2 (spatial_index default)

    # Promote ingest_snapshots to a TimescaleDB hypertable.
    # 30d chunks balance write throughput against query selectivity.
    op.execute("""
        SELECT create_hypertable(
            'ingest_snapshots',
            'snapshot_at',
            chunk_time_interval => INTERVAL '30 days',
            if_not_exists => TRUE
        )
    """)
    op.execute("""
        ALTER TABLE ingest_snapshots SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'country, is_locker',
            timescaledb.compress_orderby = 'snapshot_at DESC'
        )
    """)
    op.execute(
        "SELECT add_compression_policy('ingest_snapshots', INTERVAL '14 days', if_not_exists => TRUE)"
    )
    op.execute(
        "SELECT add_retention_policy('ingest_snapshots', INTERVAL '730 days', if_not_exists => TRUE)"
    )

    op.create_table('nuts2',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name_latn', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # idx_nuts2_geom GIST index auto-created by GeoAlchemy2 (spatial_index default)
    op.create_index(op.f('ix_nuts2_country'), 'nuts2', ['country'], unique=False)
    op.create_table('lockers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('physical_type', sa.String(length=32), nullable=True),
    sa.Column('location_247', sa.Boolean(), nullable=False),
    sa.Column('is_locker', sa.Boolean(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('gmina_teryt', sa.String(length=7), nullable=True),
    sa.Column('nuts2_id', sa.String(length=5), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gmina_teryt'], ['gminy.teryt'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nuts2_id'], ['nuts2.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # idx_lockers_geom GIST index auto-created by GeoAlchemy2 (spatial_index default)
    op.create_index(op.f('ix_lockers_content_hash'), 'lockers', ['content_hash'], unique=False)
    op.create_index(op.f('ix_lockers_country'), 'lockers', ['country'], unique=False)
    op.create_index('ix_lockers_country_is_locker', 'lockers', ['country', 'is_locker'], unique=False)
    op.create_index('ix_lockers_country_status', 'lockers', ['country', 'status'], unique=False)
    op.create_index(op.f('ix_lockers_gmina_teryt'), 'lockers', ['gmina_teryt'], unique=False)
    op.create_index(op.f('ix_lockers_is_locker'), 'lockers', ['is_locker'], unique=False)
    op.create_index(op.f('ix_lockers_name'), 'lockers', ['name'], unique=True)
    op.create_index(op.f('ix_lockers_nuts2_id'), 'lockers', ['nuts2_id'], unique=False)
    op.create_index(op.f('ix_lockers_status'), 'lockers', ['status'], unique=False)

    # H3 generated columns for hex aggregations.
    # r8 ≈ 0.7 km² hexagons — locker-density heatmap.
    # r6 ≈ 36 km² hexagons — country-level overview.
    op.execute("""
        ALTER TABLE lockers
        ADD COLUMN h3_r8 h3index
        GENERATED ALWAYS AS (h3_lat_lng_to_cell(geom::geometry::point, 8)) STORED
    """)
    op.execute("CREATE INDEX ix_lockers_h3_r8 ON lockers(h3_r8)")
    op.execute("""
        ALTER TABLE lockers
        ADD COLUMN h3_r6 h3index
        GENERATED ALWAYS AS (h3_lat_lng_to_cell(geom::geometry::point, 6)) STORED
    """)
    op.execute("CREATE INDEX ix_lockers_h3_r6 ON lockers(h3_r6)")

    op.create_table('population_gmina',
    sa.Column('teryt', sa.String(length=7), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['teryt'], ['gminy.teryt'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teryt', 'year', name='pk_population_gmina')
    )
    op.create_table('population_nuts2',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['nuts2.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code', 'year', name='pk_population_nuts2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_nuts2')
    op.drop_table('population_gmina')

    # Drop H3 generated columns + indexes before dropping lockers.
    op.execute("DROP INDEX IF EXISTS ix_lockers_h3_r6")
    op.execute("DROP INDEX IF EXISTS ix_lockers_h3_r8")
    op.execute("ALTER TABLE lockers DROP COLUMN IF EXISTS h3_r6")
    op.execute("ALTER TABLE lockers DROP COLUMN IF EXISTS h3_r8")

    op.drop_index(op.f('ix_lockers_status'), table_name='lockers')
    op.drop_index(op.f('ix_lockers_nuts2_id'), table_name='lockers')
    op.drop_index(op.f('ix_lockers_name'), table_name='lockers')
    op.drop_index(op.f('ix_lockers_is_locker'), table_name='lockers')
    op.drop_index(op.f('ix_lockers_gmina_teryt'), table_name='lockers')
    op.drop_index('ix_lockers_country_status', table_name='lockers')
    op.drop_index('ix_lockers_country_is_locker', table_name='lockers')
    op.drop_index(op.f('ix_lockers_country'), table_name='lockers')
    op.drop_index(op.f('ix_lockers_content_hash'), table_name='lockers')
    # idx_lockers_geom dropped automatically via drop_table cascade
    op.drop_table('lockers')
    op.drop_index(op.f('ix_nuts2_country'), table_name='nuts2')
    # idx_nuts2_geom dropped automatically via drop_table cascade
    op.drop_table('nuts2')
    # idx_ingest_snapshots_geom dropped automatically via drop_table cascade
    op.drop_table('ingest_snapshots')
    # idx_gminy_geom dropped automatically via drop_table cascade
    op.drop_table('gminy')
    # ### end Alembic commands ###
