// This file is auto-generated by @hey-api/openapi-ts

export const ApiResponse_CountryKpi_Schema = {
  properties: {
    data: {
      $ref: "#/components/schemas/CountryKpi",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[CountryKpi]",
} as const;

export const ApiResponse_LockerDetail_Schema = {
  properties: {
    data: {
      $ref: "#/components/schemas/LockerDetail",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[LockerDetail]",
} as const;

export const ApiResponse_NetworkSummary_Schema = {
  properties: {
    data: {
      $ref: "#/components/schemas/NetworkSummary",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[NetworkSummary]",
} as const;

export const ApiResponse_list_CountryKpi__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/CountryKpi",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[CountryKpi]]",
} as const;

export const ApiResponse_list_DensityGmina__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/DensityGmina",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[DensityGmina]]",
} as const;

export const ApiResponse_list_DensityNuts2__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/DensityNuts2",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[DensityNuts2]]",
} as const;

export const ApiResponse_list_GminaTopList__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/GminaTopList",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[GminaTopList]]",
} as const;

export const ApiResponse_list_H3Cell__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/H3Cell",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[H3Cell]]",
} as const;

export const ApiResponse_list_LockerSummary__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/LockerSummary",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[LockerSummary]]",
} as const;

export const ApiResponse_list_Nuts2TopList__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/Nuts2TopList",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[Nuts2TopList]]",
} as const;

export const ApiResponse_list_VelocityPoint__Schema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/VelocityPoint",
      },
      type: "array",
      title: "Data",
    },
    meta: {
      additionalProperties: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
          {
            type: "number",
          },
          {
            type: "null",
          },
        ],
      },
      type: "object",
      title: "Meta",
    },
  },
  type: "object",
  required: ["data"],
  title: "ApiResponse[list[VelocityPoint]]",
} as const;

export const CountryKpiSchema = {
  properties: {
    country: {
      type: "string",
      maxLength: 2,
      minLength: 2,
      title: "Country",
      description: "ISO 3166-1 alpha-2",
    },
    n_lockers: {
      type: "integer",
      minimum: 0,
      title: "N Lockers",
      description: "Operating parcel_locker machines",
    },
    n_pudo: {
      type: "integer",
      minimum: 0,
      title: "N Pudo",
      description: "Operating PUDO points",
    },
    n_total: {
      type: "integer",
      minimum: 0,
      title: "N Total",
      description: "Sum of lockers + PUDO, operating only",
    },
    n_247: {
      type: "integer",
      minimum: 0,
      title: "N 247",
      description: "24/7 accessible (operating only)",
    },
    pct_247: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Pct 247",
      description: "Percentage 24/7 of operating total",
    },
  },
  type: "object",
  required: ["country", "n_lockers", "n_pudo", "n_total", "n_247"],
  title: "CountryKpi",
  description: "Per-country headline metrics from mv_country_kpi.",
} as const;

export const DensityGminaSchema = {
  properties: {
    teryt: {
      type: "string",
      maxLength: 7,
      minLength: 7,
      title: "Teryt",
    },
    name: {
      type: "string",
      title: "Name",
    },
    voivodeship: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Voivodeship",
    },
    population: {
      type: "integer",
      minimum: 0,
      title: "Population",
    },
    n_lockers: {
      type: "integer",
      minimum: 0,
      title: "N Lockers",
    },
    n_pudo: {
      type: "integer",
      minimum: 0,
      title: "N Pudo",
    },
    lockers_per_10k: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Lockers Per 10K",
      description: "NULL when population=0",
    },
  },
  type: "object",
  required: [
    "teryt",
    "name",
    "voivodeship",
    "population",
    "n_lockers",
    "n_pudo",
  ],
  title: "DensityGmina",
  description: "One gmina row from mv_density_gmina.",
} as const;

export const DensityNuts2Schema = {
  properties: {
    code: {
      type: "string",
      maxLength: 5,
      minLength: 4,
      title: "Code",
    },
    name_latn: {
      type: "string",
      title: "Name Latn",
    },
    country: {
      type: "string",
      maxLength: 2,
      minLength: 2,
      title: "Country",
    },
    population: {
      type: "integer",
      minimum: 0,
      title: "Population",
    },
    n_lockers: {
      type: "integer",
      minimum: 0,
      title: "N Lockers",
    },
    n_pudo: {
      type: "integer",
      minimum: 0,
      title: "N Pudo",
    },
    lockers_per_10k: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Lockers Per 10K",
    },
  },
  type: "object",
  required: [
    "code",
    "name_latn",
    "country",
    "population",
    "n_lockers",
    "n_pudo",
    "lockers_per_10k",
  ],
  title: "DensityNuts2",
  description: "One NUTS-2 region row from mv_density_nuts2.",
} as const;

export const GminaTopListSchema = {
  properties: {
    teryt: {
      type: "string",
      title: "Teryt",
    },
    name: {
      type: "string",
      title: "Name",
    },
    voivodeship: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Voivodeship",
    },
    lockers_per_10k: {
      type: "number",
      title: "Lockers Per 10K",
    },
    n_lockers: {
      type: "integer",
      title: "N Lockers",
    },
    population: {
      type: "integer",
      title: "Population",
    },
  },
  type: "object",
  required: [
    "teryt",
    "name",
    "voivodeship",
    "lockers_per_10k",
    "n_lockers",
    "population",
  ],
  title: "GminaTopList",
  description: "Compact form for ranked lists.",
} as const;

export const H3CellSchema = {
  properties: {
    h3: {
      type: "string",
      title: "H3",
      description: "H3 cell index as hex string",
    },
    country: {
      type: "string",
      title: "Country",
    },
    n_lockers: {
      type: "integer",
      minimum: 0,
      title: "N Lockers",
    },
    n_pudo: {
      type: "integer",
      minimum: 0,
      title: "N Pudo",
    },
    n_total: {
      type: "integer",
      minimum: 0,
      title: "N Total",
    },
  },
  type: "object",
  required: ["h3", "country", "n_lockers", "n_pudo", "n_total"],
  title: "H3Cell",
  description: "One H3 hex with aggregated locker counts.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const LockerDetailSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    country: {
      type: "string",
      maxLength: 2,
      minLength: 2,
      title: "Country",
    },
    status: {
      type: "string",
      title: "Status",
    },
    is_locker: {
      type: "boolean",
      title: "Is Locker",
      description: "True = Paczkomat machine, False = PUDO",
    },
    physical_type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Physical Type",
    },
    location_247: {
      type: "boolean",
      title: "Location 247",
    },
    latitude: {
      type: "number",
      title: "Latitude",
    },
    longitude: {
      type: "number",
      title: "Longitude",
    },
    gmina_teryt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Gmina Teryt",
    },
    nuts2_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Nuts2 Id",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
  },
  type: "object",
  required: [
    "name",
    "country",
    "status",
    "is_locker",
    "physical_type",
    "location_247",
    "latitude",
    "longitude",
    "gmina_teryt",
    "nuts2_id",
    "updated_at",
  ],
  title: "LockerDetail",
  description: "Full locker record including admin assignment + timestamps.",
} as const;

export const LockerSummarySchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    country: {
      type: "string",
      maxLength: 2,
      minLength: 2,
      title: "Country",
    },
    status: {
      type: "string",
      title: "Status",
    },
    is_locker: {
      type: "boolean",
      title: "Is Locker",
      description: "True = Paczkomat machine, False = PUDO",
    },
    physical_type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Physical Type",
    },
    location_247: {
      type: "boolean",
      title: "Location 247",
    },
    latitude: {
      type: "number",
      title: "Latitude",
    },
    longitude: {
      type: "number",
      title: "Longitude",
    },
  },
  type: "object",
  required: [
    "name",
    "country",
    "status",
    "is_locker",
    "physical_type",
    "location_247",
    "latitude",
    "longitude",
  ],
  title: "LockerSummary",
  description: "Compact locker row for list views.",
} as const;

export const NetworkSummarySchema = {
  properties: {
    n_lockers_total: {
      type: "integer",
      title: "N Lockers Total",
    },
    n_pudo_total: {
      type: "integer",
      title: "N Pudo Total",
    },
    n_network_total: {
      type: "integer",
      title: "N Network Total",
    },
    n_countries_active: {
      type: "integer",
      title: "N Countries Active",
    },
    pl_lockers: {
      type: "integer",
      title: "Pl Lockers",
    },
    pl_pct_247: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Pl Pct 247",
    },
  },
  type: "object",
  required: [
    "n_lockers_total",
    "n_pudo_total",
    "n_network_total",
    "n_countries_active",
    "pl_lockers",
    "pl_pct_247",
  ],
  title: "NetworkSummary",
  description: "Top-line numbers for the whole network.",
} as const;

export const Nuts2TopListSchema = {
  properties: {
    code: {
      type: "string",
      title: "Code",
    },
    name_latn: {
      type: "string",
      title: "Name Latn",
    },
    country: {
      type: "string",
      title: "Country",
    },
    lockers_per_10k: {
      type: "number",
      title: "Lockers Per 10K",
    },
    n_lockers: {
      type: "integer",
      title: "N Lockers",
    },
    population: {
      type: "integer",
      title: "Population",
    },
  },
  type: "object",
  required: [
    "code",
    "name_latn",
    "country",
    "lockers_per_10k",
    "n_lockers",
    "population",
  ],
  title: "Nuts2TopList",
  description: "Compact form for ranked lists.",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const VelocityPointSchema = {
  properties: {
    country: {
      type: "string",
      title: "Country",
    },
    date: {
      type: "string",
      format: "date",
      title: "Date",
    },
    n_lockers: {
      type: "integer",
      title: "N Lockers",
    },
    source: {
      type: "string",
      title: "Source",
      default: "press_release",
    },
  },
  type: "object",
  required: ["country", "date", "n_lockers"],
  title: "VelocityPoint",
  description:
    "One (country, date, count) data point for the expansion timeline.",
} as const;
