// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetCountryKpiData,
  GetCountryKpiErrors,
  GetCountryKpiResponses,
  GetLockerData,
  GetLockerErrors,
  GetLockerResponses,
  GetNetworkSummaryData,
  GetNetworkSummaryResponses,
  GetVelocityData,
  GetVelocityErrors,
  GetVelocityResponses,
  HealthCheckData,
  HealthCheckResponses,
  ListCountryKpisData,
  ListCountryKpisResponses,
  ListGminyData,
  ListGminyErrors,
  ListGminyResponses,
  ListH3CellsData,
  ListH3CellsErrors,
  ListH3CellsResponses,
  ListLockersData,
  ListLockersErrors,
  ListLockersResponses,
  ListNuts2Data,
  ListNuts2Errors,
  ListNuts2Responses,
  RootData,
  RootResponses,
  TopGminyData,
  TopGminyErrors,
  TopGminyResponses,
  TopNuts2Data,
  TopNuts2Errors,
  TopNuts2Responses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Confirm app + DB + tile server + data freshness.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    url: "/api/v1/health",
    ...options,
  });

/**
 * Get Network Summary
 *
 * Top-line headline numbers for the landing page hero.
 */
export const getNetworkSummary = <ThrowOnError extends boolean = false>(
  options?: Options<GetNetworkSummaryData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetNetworkSummaryResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/kpi/summary", ...options });

/**
 * List Country Kpis
 *
 * All 14 active countries with operating counts.
 */
export const listCountryKpis = <ThrowOnError extends boolean = false>(
  options?: Options<ListCountryKpisData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListCountryKpisResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/kpi/countries", ...options });

/**
 * Get Country Kpi
 *
 * Single country detail.
 */
export const getCountryKpi = <ThrowOnError extends boolean = false>(
  options: Options<GetCountryKpiData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCountryKpiResponses,
    GetCountryKpiErrors,
    ThrowOnError
  >({ url: "/api/v1/kpi/countries/{country}", ...options });

/**
 * List Gminy
 *
 * Paginated list of gminy with density. Default returns up to 500 of ~2477.
 */
export const listGminy = <ThrowOnError extends boolean = false>(
  options?: Options<ListGminyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListGminyResponses,
    ListGminyErrors,
    ThrowOnError
  >({ url: "/api/v1/density/gminy", ...options });

/**
 * Top Gminy
 *
 * Top N gminy by lockers per 10k. Filtered to avoid tiny outliers.
 */
export const topGminy = <ThrowOnError extends boolean = false>(
  options?: Options<TopGminyData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TopGminyResponses,
    TopGminyErrors,
    ThrowOnError
  >({ url: "/api/v1/density/gminy/top", ...options });

/**
 * List Nuts2
 *
 * Paginated list of NUTS-2 regions with density.
 */
export const listNuts2 = <ThrowOnError extends boolean = false>(
  options?: Options<ListNuts2Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListNuts2Responses,
    ListNuts2Errors,
    ThrowOnError
  >({ url: "/api/v1/density/nuts2", ...options });

/**
 * Top Nuts2
 *
 * Top N NUTS-2 regions by lockers per 10k.
 */
export const topNuts2 = <ThrowOnError extends boolean = false>(
  options?: Options<TopNuts2Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TopNuts2Responses,
    TopNuts2Errors,
    ThrowOnError
  >({ url: "/api/v1/density/nuts2/top", ...options });

/**
 * List Lockers
 *
 * Filtered locker list. Most callers should hit the tile endpoint instead.
 */
export const listLockers = <ThrowOnError extends boolean = false>(
  options?: Options<ListLockersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListLockersResponses,
    ListLockersErrors,
    ThrowOnError
  >({ url: "/api/v1/lockers", ...options });

/**
 * Get Locker
 *
 * Single locker detail by name (e.g. WAW01N).
 */
export const getLocker = <ThrowOnError extends boolean = false>(
  options: Options<GetLockerData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLockerResponses,
    GetLockerErrors,
    ThrowOnError
  >({ url: "/api/v1/lockers/{name}", ...options });

/**
 * List H3 Cells
 *
 * H3 cells at resolution 8 with locker/PUDO counts. For tabular use.
 */
export const listH3Cells = <ThrowOnError extends boolean = false>(
  options?: Options<ListH3CellsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListH3CellsResponses,
    ListH3CellsErrors,
    ThrowOnError
  >({ url: "/api/v1/h3/cells", ...options });

/**
 * Get Velocity
 *
 * Network expansion timeline — static historical data points.
 */
export const getVelocity = <ThrowOnError extends boolean = false>(
  options?: Options<GetVelocityData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetVelocityResponses,
    GetVelocityErrors,
    ThrowOnError
  >({ url: "/api/v1/velocity", ...options });

/**
 * Root
 */
export const root = <ThrowOnError extends boolean = false>(
  options?: Options<RootData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
