// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetCountryKpiApiV1KpiCountriesCountryGetData,
  GetCountryKpiApiV1KpiCountriesCountryGetErrors,
  GetCountryKpiApiV1KpiCountriesCountryGetResponses,
  GetLockerApiV1LockersNameGetData,
  GetLockerApiV1LockersNameGetErrors,
  GetLockerApiV1LockersNameGetResponses,
  GetNetworkSummaryApiV1KpiSummaryGetData,
  GetNetworkSummaryApiV1KpiSummaryGetResponses,
  GetVelocityApiV1VelocityGetData,
  GetVelocityApiV1VelocityGetErrors,
  GetVelocityApiV1VelocityGetResponses,
  HealthApiV1HealthGetData,
  HealthApiV1HealthGetResponses,
  ListCountryKpisApiV1KpiCountriesGetData,
  ListCountryKpisApiV1KpiCountriesGetResponses,
  ListGminyApiV1DensityGminyGetData,
  ListGminyApiV1DensityGminyGetErrors,
  ListGminyApiV1DensityGminyGetResponses,
  ListH3CellsApiV1H3CellsGetData,
  ListH3CellsApiV1H3CellsGetErrors,
  ListH3CellsApiV1H3CellsGetResponses,
  ListLockersApiV1LockersGetData,
  ListLockersApiV1LockersGetErrors,
  ListLockersApiV1LockersGetResponses,
  ListNuts2ApiV1DensityNuts2GetData,
  ListNuts2ApiV1DensityNuts2GetErrors,
  ListNuts2ApiV1DensityNuts2GetResponses,
  RootGetData,
  RootGetResponses,
  TopGminyApiV1DensityGminyTopGetData,
  TopGminyApiV1DensityGminyTopGetErrors,
  TopGminyApiV1DensityGminyTopGetResponses,
  TopNuts2ApiV1DensityNuts2TopGetData,
  TopNuts2ApiV1DensityNuts2TopGetErrors,
  TopNuts2ApiV1DensityNuts2TopGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Confirm app + DB + tile server + data freshness.
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthApiV1HealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthApiV1HealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/health", ...options });

/**
 * Get Network Summary
 *
 * Top-line headline numbers for the landing page hero.
 */
export const getNetworkSummaryApiV1KpiSummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetNetworkSummaryApiV1KpiSummaryGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetNetworkSummaryApiV1KpiSummaryGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/kpi/summary", ...options });

/**
 * List Country Kpis
 *
 * All 14 active countries with operating counts.
 */
export const listCountryKpisApiV1KpiCountriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCountryKpisApiV1KpiCountriesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListCountryKpisApiV1KpiCountriesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/kpi/countries", ...options });

/**
 * Get Country Kpi
 *
 * Single country detail.
 */
export const getCountryKpiApiV1KpiCountriesCountryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCountryKpiApiV1KpiCountriesCountryGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCountryKpiApiV1KpiCountriesCountryGetResponses,
    GetCountryKpiApiV1KpiCountriesCountryGetErrors,
    ThrowOnError
  >({ url: "/api/v1/kpi/countries/{country}", ...options });

/**
 * List Gminy
 *
 * Paginated list of gminy with density. Default returns up to 500 of ~2477.
 */
export const listGminyApiV1DensityGminyGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListGminyApiV1DensityGminyGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListGminyApiV1DensityGminyGetResponses,
    ListGminyApiV1DensityGminyGetErrors,
    ThrowOnError
  >({ url: "/api/v1/density/gminy", ...options });

/**
 * Top Gminy
 *
 * Top N gminy by lockers per 10k. Filtered to avoid tiny outliers.
 */
export const topGminyApiV1DensityGminyTopGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TopGminyApiV1DensityGminyTopGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TopGminyApiV1DensityGminyTopGetResponses,
    TopGminyApiV1DensityGminyTopGetErrors,
    ThrowOnError
  >({ url: "/api/v1/density/gminy/top", ...options });

/**
 * List Nuts2
 *
 * Paginated list of NUTS-2 regions with density.
 */
export const listNuts2ApiV1DensityNuts2Get = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNuts2ApiV1DensityNuts2GetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListNuts2ApiV1DensityNuts2GetResponses,
    ListNuts2ApiV1DensityNuts2GetErrors,
    ThrowOnError
  >({ url: "/api/v1/density/nuts2", ...options });

/**
 * Top Nuts2
 *
 * Top N NUTS-2 regions by lockers per 10k.
 */
export const topNuts2ApiV1DensityNuts2TopGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TopNuts2ApiV1DensityNuts2TopGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TopNuts2ApiV1DensityNuts2TopGetResponses,
    TopNuts2ApiV1DensityNuts2TopGetErrors,
    ThrowOnError
  >({ url: "/api/v1/density/nuts2/top", ...options });

/**
 * List Lockers
 *
 * Filtered locker list. Most callers should hit the tile endpoint instead.
 */
export const listLockersApiV1LockersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLockersApiV1LockersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListLockersApiV1LockersGetResponses,
    ListLockersApiV1LockersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lockers", ...options });

/**
 * Get Locker
 *
 * Single locker detail by name (e.g. WAW01N).
 */
export const getLockerApiV1LockersNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLockerApiV1LockersNameGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLockerApiV1LockersNameGetResponses,
    GetLockerApiV1LockersNameGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lockers/{name}", ...options });

/**
 * List H3 Cells
 *
 * H3 cells at resolution 8 with locker/PUDO counts. For tabular use.
 */
export const listH3CellsApiV1H3CellsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListH3CellsApiV1H3CellsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListH3CellsApiV1H3CellsGetResponses,
    ListH3CellsApiV1H3CellsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/h3/cells", ...options });

/**
 * Get Velocity
 *
 * Network expansion timeline — static historical data points.
 */
export const getVelocityApiV1VelocityGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetVelocityApiV1VelocityGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetVelocityApiV1VelocityGetResponses,
    GetVelocityApiV1VelocityGetErrors,
    ThrowOnError
  >({ url: "/api/v1/velocity", ...options });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
