// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

/**
 * ApiResponse[CountryKpi]
 */
export type ApiResponseCountryKpi = {
  data: CountryKpi;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[LockerDetail]
 */
export type ApiResponseLockerDetail = {
  data: LockerDetail;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[NetworkSummary]
 */
export type ApiResponseNetworkSummary = {
  data: NetworkSummary;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[CountryKpi]]
 */
export type ApiResponseListCountryKpi = {
  /**
   * Data
   */
  data: Array<CountryKpi>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[DensityGmina]]
 */
export type ApiResponseListDensityGmina = {
  /**
   * Data
   */
  data: Array<DensityGmina>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[DensityNuts2]]
 */
export type ApiResponseListDensityNuts2 = {
  /**
   * Data
   */
  data: Array<DensityNuts2>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[GminaTopList]]
 */
export type ApiResponseListGminaTopList = {
  /**
   * Data
   */
  data: Array<GminaTopList>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[H3Cell]]
 */
export type ApiResponseListH3Cell = {
  /**
   * Data
   */
  data: Array<H3Cell>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[LockerSummary]]
 */
export type ApiResponseListLockerSummary = {
  /**
   * Data
   */
  data: Array<LockerSummary>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[Nuts2TopList]]
 */
export type ApiResponseListNuts2TopList = {
  /**
   * Data
   */
  data: Array<Nuts2TopList>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[VelocityPoint]]
 */
export type ApiResponseListVelocityPoint = {
  /**
   * Data
   */
  data: Array<VelocityPoint>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * CountryKpi
 *
 * Per-country headline metrics from mv_country_kpi.
 */
export type CountryKpi = {
  /**
   * Country
   *
   * ISO 3166-1 alpha-2
   */
  country: string;
  /**
   * N Lockers
   *
   * Operating parcel_locker machines
   */
  n_lockers: number;
  /**
   * N Pudo
   *
   * Operating PUDO points
   */
  n_pudo: number;
  /**
   * N Total
   *
   * Sum of lockers + PUDO, operating only
   */
  n_total: number;
  /**
   * N 247
   *
   * 24/7 accessible (operating only)
   */
  n_247: number;
  /**
   * Pct 247
   *
   * Percentage 24/7 of operating total
   */
  pct_247?: number | null;
};

/**
 * DensityGmina
 *
 * One gmina row from mv_density_gmina.
 */
export type DensityGmina = {
  /**
   * Teryt
   */
  teryt: string;
  /**
   * Name
   */
  name: string;
  /**
   * Voivodeship
   */
  voivodeship: string | null;
  /**
   * Population
   */
  population: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * Lockers Per 10K
   *
   * NULL when population=0
   */
  lockers_per_10k?: number | null;
};

/**
 * DensityNuts2
 *
 * One NUTS-2 region row from mv_density_nuts2.
 */
export type DensityNuts2 = {
  /**
   * Code
   */
  code: string;
  /**
   * Name Latn
   */
  name_latn: string;
  /**
   * Country
   */
  country: string;
  /**
   * Population
   */
  population: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number | null;
};

/**
 * GminaTopList
 *
 * Compact form for ranked lists.
 */
export type GminaTopList = {
  /**
   * Teryt
   */
  teryt: string;
  /**
   * Name
   */
  name: string;
  /**
   * Voivodeship
   */
  voivodeship: string | null;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Population
   */
  population: number;
};

/**
 * H3Cell
 *
 * One H3 hex with aggregated locker counts.
 */
export type H3Cell = {
  /**
   * H3
   *
   * H3 cell index as hex string
   */
  h3: string;
  /**
   * Country
   */
  country: string;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * N Total
   */
  n_total: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LockerDetail
 *
 * Full locker record including admin assignment + timestamps.
 */
export type LockerDetail = {
  /**
   * Name
   */
  name: string;
  /**
   * Country
   */
  country: string;
  /**
   * Status
   */
  status: string;
  /**
   * Is Locker
   *
   * True = Paczkomat machine, False = PUDO
   */
  is_locker: boolean;
  /**
   * Physical Type
   */
  physical_type: string | null;
  /**
   * Location 247
   */
  location_247: boolean;
  /**
   * Latitude
   */
  latitude: number;
  /**
   * Longitude
   */
  longitude: number;
  /**
   * Gmina Teryt
   */
  gmina_teryt: string | null;
  /**
   * Nuts2 Id
   */
  nuts2_id: string | null;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * LockerSummary
 *
 * Compact locker row for list views.
 */
export type LockerSummary = {
  /**
   * Name
   */
  name: string;
  /**
   * Country
   */
  country: string;
  /**
   * Status
   */
  status: string;
  /**
   * Is Locker
   *
   * True = Paczkomat machine, False = PUDO
   */
  is_locker: boolean;
  /**
   * Physical Type
   */
  physical_type: string | null;
  /**
   * Location 247
   */
  location_247: boolean;
  /**
   * Latitude
   */
  latitude: number;
  /**
   * Longitude
   */
  longitude: number;
};

/**
 * NetworkSummary
 *
 * Top-line numbers for the whole network.
 */
export type NetworkSummary = {
  /**
   * N Lockers Total
   */
  n_lockers_total: number;
  /**
   * N Pudo Total
   */
  n_pudo_total: number;
  /**
   * N Network Total
   */
  n_network_total: number;
  /**
   * N Countries Active
   */
  n_countries_active: number;
  /**
   * Pl Lockers
   */
  pl_lockers: number;
  /**
   * Pl Pct 247
   */
  pl_pct_247: number | null;
};

/**
 * Nuts2TopList
 *
 * Compact form for ranked lists.
 */
export type Nuts2TopList = {
  /**
   * Code
   */
  code: string;
  /**
   * Name Latn
   */
  name_latn: string;
  /**
   * Country
   */
  country: string;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Population
   */
  population: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * VelocityPoint
 *
 * One (country, date, count) data point for the expansion timeline.
 */
export type VelocityPoint = {
  /**
   * Country
   */
  country: string;
  /**
   * Date
   */
  date: string;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Source
   */
  source?: string;
};

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/health";
};

export type HealthCheckResponses = {
  /**
   * Response Healthcheck
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type HealthCheckResponse =
  HealthCheckResponses[keyof HealthCheckResponses];

export type GetNetworkSummaryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/kpi/summary";
};

export type GetNetworkSummaryResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseNetworkSummary;
};

export type GetNetworkSummaryResponse =
  GetNetworkSummaryResponses[keyof GetNetworkSummaryResponses];

export type ListCountryKpisData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/kpi/countries";
};

export type ListCountryKpisResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListCountryKpi;
};

export type ListCountryKpisResponse =
  ListCountryKpisResponses[keyof ListCountryKpisResponses];

export type GetCountryKpiData = {
  body?: never;
  path: {
    /**
     * Country
     */
    country: string;
  };
  query?: never;
  url: "/api/v1/kpi/countries/{country}";
};

export type GetCountryKpiErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCountryKpiError = GetCountryKpiErrors[keyof GetCountryKpiErrors];

export type GetCountryKpiResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseCountryKpi;
};

export type GetCountryKpiResponse =
  GetCountryKpiResponses[keyof GetCountryKpiResponses];

export type ListGminyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Voivodeship
     *
     * Filter by voivodeship name
     */
    voivodeship?: string | null;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/density/gminy";
};

export type ListGminyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListGminyError = ListGminyErrors[keyof ListGminyErrors];

export type ListGminyResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListDensityGmina;
};

export type ListGminyResponse = ListGminyResponses[keyof ListGminyResponses];

export type TopGminyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Min Lockers
     */
    min_lockers?: number;
  };
  url: "/api/v1/density/gminy/top";
};

export type TopGminyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TopGminyError = TopGminyErrors[keyof TopGminyErrors];

export type TopGminyResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListGminaTopList;
};

export type TopGminyResponse = TopGminyResponses[keyof TopGminyResponses];

export type ListNuts2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/density/nuts2";
};

export type ListNuts2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListNuts2Error = ListNuts2Errors[keyof ListNuts2Errors];

export type ListNuts2Responses = {
  /**
   * Successful Response
   */
  200: ApiResponseListDensityNuts2;
};

export type ListNuts2Response = ListNuts2Responses[keyof ListNuts2Responses];

export type TopNuts2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Min Population
     */
    min_population?: number;
  };
  url: "/api/v1/density/nuts2/top";
};

export type TopNuts2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TopNuts2Error = TopNuts2Errors[keyof TopNuts2Errors];

export type TopNuts2Responses = {
  /**
   * Successful Response
   */
  200: ApiResponseListNuts2TopList;
};

export type TopNuts2Response = TopNuts2Responses[keyof TopNuts2Responses];

export type ListLockersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Is Locker
     */
    is_locker?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Location 247
     */
    location_247?: boolean | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/lockers";
};

export type ListLockersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLockersError = ListLockersErrors[keyof ListLockersErrors];

export type ListLockersResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListLockerSummary;
};

export type ListLockersResponse =
  ListLockersResponses[keyof ListLockersResponses];

export type GetLockerData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/api/v1/lockers/{name}";
};

export type GetLockerErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLockerError = GetLockerErrors[keyof GetLockerErrors];

export type GetLockerResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLockerDetail;
};

export type GetLockerResponse = GetLockerResponses[keyof GetLockerResponses];

export type ListH3CellsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Min Count
     */
    min_count?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/h3/cells";
};

export type ListH3CellsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListH3CellsError = ListH3CellsErrors[keyof ListH3CellsErrors];

export type ListH3CellsResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListH3Cell;
};

export type ListH3CellsResponse =
  ListH3CellsResponses[keyof ListH3CellsResponses];

export type GetVelocityData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
  };
  url: "/api/v1/velocity";
};

export type GetVelocityErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetVelocityError = GetVelocityErrors[keyof GetVelocityErrors];

export type GetVelocityResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListVelocityPoint;
};

export type GetVelocityResponse =
  GetVelocityResponses[keyof GetVelocityResponses];

export type RootData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootResponses = {
  /**
   * Response Root
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type RootResponse = RootResponses[keyof RootResponses];
