// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

/**
 * ApiResponse[CountryKpi]
 */
export type ApiResponseCountryKpi = {
  data: CountryKpi;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[LockerDetail]
 */
export type ApiResponseLockerDetail = {
  data: LockerDetail;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[NetworkSummary]
 */
export type ApiResponseNetworkSummary = {
  data: NetworkSummary;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[CountryKpi]]
 */
export type ApiResponseListCountryKpi = {
  /**
   * Data
   */
  data: Array<CountryKpi>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[DensityGmina]]
 */
export type ApiResponseListDensityGmina = {
  /**
   * Data
   */
  data: Array<DensityGmina>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[DensityNuts2]]
 */
export type ApiResponseListDensityNuts2 = {
  /**
   * Data
   */
  data: Array<DensityNuts2>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[GminaTopList]]
 */
export type ApiResponseListGminaTopList = {
  /**
   * Data
   */
  data: Array<GminaTopList>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[H3Cell]]
 */
export type ApiResponseListH3Cell = {
  /**
   * Data
   */
  data: Array<H3Cell>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[LockerSummary]]
 */
export type ApiResponseListLockerSummary = {
  /**
   * Data
   */
  data: Array<LockerSummary>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[Nuts2TopList]]
 */
export type ApiResponseListNuts2TopList = {
  /**
   * Data
   */
  data: Array<Nuts2TopList>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * ApiResponse[list[VelocityPoint]]
 */
export type ApiResponseListVelocityPoint = {
  /**
   * Data
   */
  data: Array<VelocityPoint>;
  /**
   * Meta
   */
  meta?: {
    [key: string]: string | number | number | null;
  };
};

/**
 * CountryKpi
 *
 * Per-country headline metrics from mv_country_kpi.
 */
export type CountryKpi = {
  /**
   * Country
   *
   * ISO 3166-1 alpha-2
   */
  country: string;
  /**
   * N Lockers
   *
   * Operating parcel_locker machines
   */
  n_lockers: number;
  /**
   * N Pudo
   *
   * Operating PUDO points
   */
  n_pudo: number;
  /**
   * N Total
   *
   * Sum of lockers + PUDO, operating only
   */
  n_total: number;
  /**
   * N 247
   *
   * 24/7 accessible (operating only)
   */
  n_247: number;
  /**
   * Pct 247
   *
   * Percentage 24/7 of operating total
   */
  pct_247?: number | null;
};

/**
 * DensityGmina
 *
 * One gmina row from mv_density_gmina.
 */
export type DensityGmina = {
  /**
   * Teryt
   */
  teryt: string;
  /**
   * Name
   */
  name: string;
  /**
   * Voivodeship
   */
  voivodeship: string | null;
  /**
   * Population
   */
  population: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * Lockers Per 10K
   *
   * NULL when population=0
   */
  lockers_per_10k?: number | null;
};

/**
 * DensityNuts2
 *
 * One NUTS-2 region row from mv_density_nuts2.
 */
export type DensityNuts2 = {
  /**
   * Code
   */
  code: string;
  /**
   * Name Latn
   */
  name_latn: string;
  /**
   * Country
   */
  country: string;
  /**
   * Population
   */
  population: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number | null;
};

/**
 * GminaTopList
 *
 * Compact form for ranked lists.
 */
export type GminaTopList = {
  /**
   * Teryt
   */
  teryt: string;
  /**
   * Name
   */
  name: string;
  /**
   * Voivodeship
   */
  voivodeship: string | null;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Population
   */
  population: number;
};

/**
 * H3Cell
 *
 * One H3 hex with aggregated locker counts.
 */
export type H3Cell = {
  /**
   * H3
   *
   * H3 cell index as hex string
   */
  h3: string;
  /**
   * Country
   */
  country: string;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * N Pudo
   */
  n_pudo: number;
  /**
   * N Total
   */
  n_total: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LockerDetail
 *
 * Full locker record including admin assignment + timestamps.
 */
export type LockerDetail = {
  /**
   * Name
   */
  name: string;
  /**
   * Country
   */
  country: string;
  /**
   * Status
   */
  status: string;
  /**
   * Is Locker
   *
   * True = Paczkomat machine, False = PUDO
   */
  is_locker: boolean;
  /**
   * Physical Type
   */
  physical_type: string | null;
  /**
   * Location 247
   */
  location_247: boolean;
  /**
   * Latitude
   */
  latitude: number;
  /**
   * Longitude
   */
  longitude: number;
  /**
   * Gmina Teryt
   */
  gmina_teryt: string | null;
  /**
   * Nuts2 Id
   */
  nuts2_id: string | null;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * LockerSummary
 *
 * Compact locker row for list views.
 */
export type LockerSummary = {
  /**
   * Name
   */
  name: string;
  /**
   * Country
   */
  country: string;
  /**
   * Status
   */
  status: string;
  /**
   * Is Locker
   *
   * True = Paczkomat machine, False = PUDO
   */
  is_locker: boolean;
  /**
   * Physical Type
   */
  physical_type: string | null;
  /**
   * Location 247
   */
  location_247: boolean;
  /**
   * Latitude
   */
  latitude: number;
  /**
   * Longitude
   */
  longitude: number;
};

/**
 * NetworkSummary
 *
 * Top-line numbers for the whole network.
 */
export type NetworkSummary = {
  /**
   * N Lockers Total
   */
  n_lockers_total: number;
  /**
   * N Pudo Total
   */
  n_pudo_total: number;
  /**
   * N Network Total
   */
  n_network_total: number;
  /**
   * N Countries Active
   */
  n_countries_active: number;
  /**
   * Pl Lockers
   */
  pl_lockers: number;
  /**
   * Pl Pct 247
   */
  pl_pct_247: number | null;
};

/**
 * Nuts2TopList
 *
 * Compact form for ranked lists.
 */
export type Nuts2TopList = {
  /**
   * Code
   */
  code: string;
  /**
   * Name Latn
   */
  name_latn: string;
  /**
   * Country
   */
  country: string;
  /**
   * Lockers Per 10K
   */
  lockers_per_10k: number;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Population
   */
  population: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * VelocityPoint
 *
 * One (country, date, count) data point for the expansion timeline.
 */
export type VelocityPoint = {
  /**
   * Country
   */
  country: string;
  /**
   * Date
   */
  date: string;
  /**
   * N Lockers
   */
  n_lockers: number;
  /**
   * Source
   */
  source?: string;
};

export type HealthApiV1HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/health";
};

export type HealthApiV1HealthGetResponses = {
  /**
   * Response Health Api V1 Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type HealthApiV1HealthGetResponse =
  HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type GetNetworkSummaryApiV1KpiSummaryGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/kpi/summary";
};

export type GetNetworkSummaryApiV1KpiSummaryGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseNetworkSummary;
};

export type GetNetworkSummaryApiV1KpiSummaryGetResponse =
  GetNetworkSummaryApiV1KpiSummaryGetResponses[keyof GetNetworkSummaryApiV1KpiSummaryGetResponses];

export type ListCountryKpisApiV1KpiCountriesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/kpi/countries";
};

export type ListCountryKpisApiV1KpiCountriesGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListCountryKpi;
};

export type ListCountryKpisApiV1KpiCountriesGetResponse =
  ListCountryKpisApiV1KpiCountriesGetResponses[keyof ListCountryKpisApiV1KpiCountriesGetResponses];

export type GetCountryKpiApiV1KpiCountriesCountryGetData = {
  body?: never;
  path: {
    /**
     * Country
     */
    country: string;
  };
  query?: never;
  url: "/api/v1/kpi/countries/{country}";
};

export type GetCountryKpiApiV1KpiCountriesCountryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCountryKpiApiV1KpiCountriesCountryGetError =
  GetCountryKpiApiV1KpiCountriesCountryGetErrors[keyof GetCountryKpiApiV1KpiCountriesCountryGetErrors];

export type GetCountryKpiApiV1KpiCountriesCountryGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseCountryKpi;
};

export type GetCountryKpiApiV1KpiCountriesCountryGetResponse =
  GetCountryKpiApiV1KpiCountriesCountryGetResponses[keyof GetCountryKpiApiV1KpiCountriesCountryGetResponses];

export type ListGminyApiV1DensityGminyGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Voivodeship
     *
     * Filter by voivodeship name
     */
    voivodeship?: string | null;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/density/gminy";
};

export type ListGminyApiV1DensityGminyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListGminyApiV1DensityGminyGetError =
  ListGminyApiV1DensityGminyGetErrors[keyof ListGminyApiV1DensityGminyGetErrors];

export type ListGminyApiV1DensityGminyGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListDensityGmina;
};

export type ListGminyApiV1DensityGminyGetResponse =
  ListGminyApiV1DensityGminyGetResponses[keyof ListGminyApiV1DensityGminyGetResponses];

export type TopGminyApiV1DensityGminyTopGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Min Lockers
     */
    min_lockers?: number;
  };
  url: "/api/v1/density/gminy/top";
};

export type TopGminyApiV1DensityGminyTopGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TopGminyApiV1DensityGminyTopGetError =
  TopGminyApiV1DensityGminyTopGetErrors[keyof TopGminyApiV1DensityGminyTopGetErrors];

export type TopGminyApiV1DensityGminyTopGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListGminaTopList;
};

export type TopGminyApiV1DensityGminyTopGetResponse =
  TopGminyApiV1DensityGminyTopGetResponses[keyof TopGminyApiV1DensityGminyTopGetResponses];

export type ListNuts2ApiV1DensityNuts2GetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Min Population
     */
    min_population?: number;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/density/nuts2";
};

export type ListNuts2ApiV1DensityNuts2GetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListNuts2ApiV1DensityNuts2GetError =
  ListNuts2ApiV1DensityNuts2GetErrors[keyof ListNuts2ApiV1DensityNuts2GetErrors];

export type ListNuts2ApiV1DensityNuts2GetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListDensityNuts2;
};

export type ListNuts2ApiV1DensityNuts2GetResponse =
  ListNuts2ApiV1DensityNuts2GetResponses[keyof ListNuts2ApiV1DensityNuts2GetResponses];

export type TopNuts2ApiV1DensityNuts2TopGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Min Population
     */
    min_population?: number;
  };
  url: "/api/v1/density/nuts2/top";
};

export type TopNuts2ApiV1DensityNuts2TopGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TopNuts2ApiV1DensityNuts2TopGetError =
  TopNuts2ApiV1DensityNuts2TopGetErrors[keyof TopNuts2ApiV1DensityNuts2TopGetErrors];

export type TopNuts2ApiV1DensityNuts2TopGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListNuts2TopList;
};

export type TopNuts2ApiV1DensityNuts2TopGetResponse =
  TopNuts2ApiV1DensityNuts2TopGetResponses[keyof TopNuts2ApiV1DensityNuts2TopGetResponses];

export type ListLockersApiV1LockersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Is Locker
     */
    is_locker?: boolean | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Location 247
     */
    location_247?: boolean | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/lockers";
};

export type ListLockersApiV1LockersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListLockersApiV1LockersGetError =
  ListLockersApiV1LockersGetErrors[keyof ListLockersApiV1LockersGetErrors];

export type ListLockersApiV1LockersGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListLockerSummary;
};

export type ListLockersApiV1LockersGetResponse =
  ListLockersApiV1LockersGetResponses[keyof ListLockersApiV1LockersGetResponses];

export type GetLockerApiV1LockersNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/api/v1/lockers/{name}";
};

export type GetLockerApiV1LockersNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLockerApiV1LockersNameGetError =
  GetLockerApiV1LockersNameGetErrors[keyof GetLockerApiV1LockersNameGetErrors];

export type GetLockerApiV1LockersNameGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseLockerDetail;
};

export type GetLockerApiV1LockersNameGetResponse =
  GetLockerApiV1LockersNameGetResponses[keyof GetLockerApiV1LockersNameGetResponses];

export type ListH3CellsApiV1H3CellsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
    /**
     * Min Count
     */
    min_count?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/h3/cells";
};

export type ListH3CellsApiV1H3CellsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListH3CellsApiV1H3CellsGetError =
  ListH3CellsApiV1H3CellsGetErrors[keyof ListH3CellsApiV1H3CellsGetErrors];

export type ListH3CellsApiV1H3CellsGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListH3Cell;
};

export type ListH3CellsApiV1H3CellsGetResponse =
  ListH3CellsApiV1H3CellsGetResponses[keyof ListH3CellsApiV1H3CellsGetResponses];

export type GetVelocityApiV1VelocityGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Country
     */
    country?: string | null;
  };
  url: "/api/v1/velocity";
};

export type GetVelocityApiV1VelocityGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetVelocityApiV1VelocityGetError =
  GetVelocityApiV1VelocityGetErrors[keyof GetVelocityApiV1VelocityGetErrors];

export type GetVelocityApiV1VelocityGetResponses = {
  /**
   * Successful Response
   */
  200: ApiResponseListVelocityPoint;
};

export type GetVelocityApiV1VelocityGetResponse =
  GetVelocityApiV1VelocityGetResponses[keyof GetVelocityApiV1VelocityGetResponses];

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Response Root  Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];
